name: call shared one

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: anish-test/shared-workflow/.github/workflows/main.yml@main
    secrets: inherit
    with:
      MANIFEST_APP_NAME: ${{ vars.MANIFEST_APP_NAME }}